title: Site
preset: pages
unlisted: true

fields:
  staticSiteGenerator:
    label: Generate a static version of the site
    label: Generate static site
    help: Custom help text
    progress: Custom please-wait message
    success: Custom success message
    error: Custom error message
